source 'https://rubygems.org'
gem 'monban'
gem 'monban-generators'
gem 'kaminari'
gem 'bitters'
gem 'bourbon'
gem 'neat'
gem 'rails', '4.1.1'
gem 'pg'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'spring',        group: :development
gem 'rails_12factor'
gem 'newrelic_rpm'

